import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const goRoot = process.env.GOROOT126 ?? resolve(root, ".research/go1.26.4-full/go");
const go = process.env.GO126 ?? resolve(goRoot, "bin/go.exe");
const packages = ["strings", "strconv", "sort", "math", "bytes"];
const raw = execFileSync(go, ["run", "./tools/extract-stdlib/main.go", ...packages], {
  cwd: root,
  encoding: "utf8",
  env: {
    ...process.env,
    GOROOT: goRoot,
  },
});
const catalog = JSON.parse(raw);
const toolchain = execFileSync(go, ["version"], {
  encoding: "utf8",
  env: {
    ...process.env,
    GOROOT: goRoot,
  },
}).trim();
writeFileSync(
  resolve(root, "src/data/stdlib.generated.js"),
  `// Generated by tools/extract-stdlib.mjs with Go 1.26.4. Do not edit.\n`
    + `export const standardLibraryMetadata = Object.freeze(${JSON.stringify({
      toolchain,
      packages,
      functionCount: Object.values(catalog).flat().length,
    }, null, 2)});\n\n`
    + `export const standardLibrary = Object.freeze(${JSON.stringify(catalog, null, 2)});\n`,
  "utf8",
);
console.log(`wrote ${Object.values(catalog).flat().length} standard-library functions`);
